### ISSUE TITLE
Skipping progress bar - no such file to load -- progress_bar

### ISSUE THREAD

**Issue by maslof** [hybridindie/spree_sunspot_search#1]
Hello!

With rake sunspot:solr:reindex error:

rake sunspot:solr:reindex --trace
*\* Invoke sunspot:solr:reindex (first_time)
*\* Invoke sunspot:reindex (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute sunspot:reindex
Skipping progress bar - no such file to load -- progress_bar
*\* Execute sunspot:solr:reindex

If add gem 'progress_bar' in Gemfile 

rake sunspot:solr:reindex
rake aborted!
no such file to load -- options

Please help me

**Comment by hybridindie** [comment]
install the progress_bar gem - please note this software should be considered pre-alpha. I am actively working on this and it is a moving target

**Comment by maslof** [comment]
"install the progress_bar gem" didn't help...rake sunspot:solr:reindex

rake aborted!
no such file to load -- options

Thanks, I'll wait

**Comment by jamiebuchanan** [comment]
+1 on this. was working fine until we upgraded to 'terminitor', '~>0.6.1'
